services:
  - type: web
    name: ruh-backend
    env: ruby
    region: oregon
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec rackup config.ru -p $PORT -o 0.0.0.0
    runtime: ruby
    runtimeVersion: 3.2.2
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: RACK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ruh-db
          property: connectionString

  - type: postgres
    name: ruh-db
    region: oregon
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction 